export class Hospital {
    name:String
    hospitalType:String
    accreditation:String
    providerType:String[]
    registrationNo:String
    address:String
    pincode:String
    district:String
    state:String
    landline:String
    mobile:String
    emergencyNo:String
    ambulanceNo:String
    bloodBankNo:String
    tollFree:String
    primaryEmailId:String
    secondaryEmailId:String
    website:String
    personnelName:String
    personnelNo:String
    personnelEmail:String
}
